<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Introducción a TensorFlow 2.0.</font>

### Historia de TensorFlow
Hace un par de años, el aprendizaje profundo comenzó a superar a todos los demás algoritmos de aprendizaje automático al dar una gran cantidad de datos. Google vio que podía usar estas redes neuronales profundas para mejorar sus servicios:

- Gmail
- Foto
- Motor de búsqueda de Google

Construyen un marco llamado Tensorflow para permitir que investigadores y desarrolladores trabajen juntos en un modelo de IA. Una vez desarrollado y escalado, permite a mucha gente usarlo.

Se hizo público por primera vez a finales de 2015, mientras que la primera versión estable apareció en 2017. Es de código abierto bajo licencia Apache Open Source. 


### Arquitectura TensorFlow
La arquitectura de Tensorflow funciona en tres partes:

>Procesamiento previo de los datos
>Construir el modelo
>Entrenar y estimar el modelo

Se llama Tensorflow porque toma entrada como una matriz multidimensional, también conocida como tensores. Puede construir una especie de diagrama de flujo de operaciones (llamado Graph) que desea realizar en esa entrada. La entrada entra en un extremo, y luego fluye a través de este sistema de múltiples operaciones y sale el otro extremo como salida.

### Introducción a los componentes de TensorFlow

#### Tensor

>El nombre de Tensorflow se deriva directamente de su marco principal: Tensor. En Tensorflow, todos los cálculos involucran tensores. Un tensor es un vector o matriz de n-dimensiones que representa todos los tipos de datos. Todos los valores de un tensor contienen un tipo de datos idéntico con una forma conocida (o parcialmente conocida). La forma de los datos es la dimensionalidad de la matriz o matriz.

>Un tensor puede originarse a partir de los datos de entrada o del resultado de un cálculo. En TensorFlow, todas las operaciones se llevan a cabo dentro de un gráfico. El gráfico es un conjunto de cálculo que tiene lugar sucesivamente. Cada operación se llama un nodo op y están conectados entre sí.

>El gráfico describe las operaciones y las conexiones entre los nodos. Sin embargo, no muestra los valores. El borde de los nodos es el tensor, es decir, una forma de llenar la operación con datos.

#### Gráficos

>TensorFlow hace uso de un marco gráfico. El gráfico recoge y describe todos los cálculos de series realizados durante el entrenamiento. El gráfico tiene muchas ventajas:

- Se hizo para ejecutarse en múltiples CPU o GPU e incluso en el sistema operativo móvil
- La portabilidad del gráfico permite conservar los cálculos para uso inmediato o posterior. El gráfico se puede guardar para ser ejecutado en el futuro.
- Todos los cálculos en el gráfico se realizan conectando tensores juntos
- Un tensor tiene un nodo y un borde. El nodo lleva la operación matemática y produce una salida de puntos finales. Los bordes de los bordes explican las relaciones de entrada/salida entre nodos.

### Lista de algoritmos prominentes soportados por TensorFlow

Actualmente, TensorFlow 1.10 tiene una API integrada para:

- Regresión lineal: tf.estimator.linearRegresor
- clasificación:tf.estimator.linearClassifier
- Clasificación de aprendizaje profundo: TF.Estimator.DNNClassifier
- Deep learning wipe and deep: tf.Estimator.dnnLinearCombinedClassifier
- Regresión del árbol de refuerzo: TF.Estimator.BoostedTreesRegressor
- Clasificación de árboles potenciados: TF.Estimator.BoostedTreesClassifier

## Tipos de tensores

En TensorFlow, todos los cálculos pasan a través de uno o más tensores. Un tensor es un objeto con tres propiedades:

- Una etiqueta única (nombre)
- Una cota (forma)
- Un tipo de datos (dtype)

Cada operación que realizará con TensorFlow implica la manipulación de un tensor. Hay cuatro tensores principales que puedes crear:

>tf.Variable

>tf.constante

>tf.placeholder

>TF.Sparsetensor


## TensorFlow 2.0

### Instalar TensorFlow 2.0

!pip install tensorflow==2.2.0 --user

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
tf.__version__

'2.2.0'

### Crear un tensor de dimensión n
Comienza con la creación de un tensor con una dimensión, es decir, un escalar.

Para crear un tensor, puede usar tf.constant ()

`tf.constant(value, dtype, name = "")
arguments

- `value`: Value of n dimension to define the tensor. Optional
- `dtype`: Define the type of data:    
    - `tf.string`: String variable    
    - `tf.float32`: Flot variable    
    - `tf.int16`: Integer variable
- "name": Name of the tensor. Optional. By default, `Const_1:0``

### Tensor de dimensión 0

In [5]:
## rank 0
# Default name
r1 = tf.constant(1,tf.int16)
print(r1)

tf.Tensor(1, shape=(), dtype=int16)


In [6]:
# Named my_scalar
r1 = tf.constant(1,tf.int16, name= "mi_escalar")
print(r1)

tf.Tensor(1, shape=(), dtype=int16)


Cada tensor se muestra con el nombre del tensor. Cada objeto tensor se define con una etiqueta única (nombre), una dimensión (forma) y un tipo de datos (dtype).

Puede definir un tensor con valores decimales o con una cadena cambiando el tipo de datos.

In [7]:
# Decimal
r1_decimal = tf.constant(1.2343, tf.float32)
print(r1_decimal)

tf.Tensor(1.2343, shape=(), dtype=float32)


In [8]:
#strring
r1_string = tf.constant("hola", tf.string)
print(r1_string)

tf.Tensor(b'hola', shape=(), dtype=string)


Se puede crear un tensor de la dimensión 1 de la siguiente manera:

In [9]:
## Rank 1
r1_vector = tf.constant([1,2,3,4], tf.int16)
print(r1_vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int16)


In [10]:
r1_bool = tf.constant([True,False,True], tf.bool)
print(r1_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


Puede observar que la forma sólo está compuesta por 1 columna.

Para crear una matriz de 2 dimensiones, debe cerrar los corchetes después de cada fila. Echa un vistazo a los ejemplos siguientes

In [11]:
## Rank 2
r2_matrix = tf.constant([[1,2],[3,4]], tf.int16)
print(r2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


#### Forma del tensor
Cuando se imprime el tensor, TensorFlow adivina la forma. Sin embargo, puede obtener la forma del tensor con la propiedad shape.

A continuación, se construye una matriz llena con un número del 10 al 15 y se comprueba la forma de m_shape

In [13]:
# Shape of tensor
m_shape=tf.constant([[10,11],
                    [12,13],
                    [14,15]])
print(m_shape)

tf.Tensor(
[[10 11]
 [12 13]
 [14 15]], shape=(3, 2), dtype=int32)


In [14]:
m_shape.shape

TensorShape([3, 2])

La matriz tiene 3 filas y 2 columnas.

TensorFlow tiene comandos útiles para crear un vector o una matriz llena con 0 o 1. Por ejemplo, si desea crear un tensor 1-D con una forma específica de 10, rellenado con 0, puede ejecutar el siguiente código:

In [16]:
# Create a vector of 0
print(tf.zeros(10))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


La propiedad también funciona para matriz. Aquí, crea una matriz 10×10 llena de 1

In [17]:
# Create a vector of 1
print(tf.ones(10))

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [18]:
print(tf.ones([10,10]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


Puede usar la forma de una matriz dada para hacer un vector de unos. La matriz m_shape es una dimensión 3×2. Puede crear un tensor con 3 filas rellenadas por uno con el siguiente código:

In [20]:
# Create a vector of ones with the same number of rows as m_shape
m_shape.shape

TensorShape([3, 2])

In [22]:
print(tf.ones(m_shape.shape[0]))

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [23]:
print(tf.ones(m_shape.shape[1]))

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [24]:
print(tf.ones([m_shape.shape[0], m_shape.shape[1]]))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [25]:
[m_shape.shape[0], m_shape.shape[1]]

[3, 2]

Si pasa el valor 1 en el corchete, puede construir un vector de unos igual al número de columnas en la matriz m_shape.

In [26]:
# Create a vector of ones with the same number of column as m_shape
print(tf.ones(m_shape.shape))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Finalmente, puede crear una matriz 3×2 con solo una

### Tipo de datos
La segunda propiedad de un tensor es el tipo de datos. Un tensor solo puede tener un tipo de datos a la vez. Un tensor solo puede tener un tipo de datos. Puede devolver el tipo con la propiedad dtype.

In [27]:
m_shape.dtype

tf.int32

En algunas ocasiones, desea cambiar el tipo de datos. En TensorFlow, es posible con el método tf.cast.

###### Ejemplo

A continuación, un tensor flotante se convierte en entero utilizando el método de conversión.

In [29]:
# Change type of data
type_float = tf.constant(3.1416, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)


In [31]:
type_float.dtype

tf.float32

In [32]:
type_int.dtype

tf.int32

TensorFlow elige automáticamente el tipo de datos cuando el argumento no se especifica durante la creación del tensor. TensorFlow adivinará cuáles son los tipos de datos más probables. Por ejemplo, si pasa un texto, adivinará que es una cadena y la convertirá en cadena.

#### Creando operador
##### Algunos operadores TensorFlow útiles
Sabes cómo crear un tensor con TensorFlow. Es hora de aprender a realizar operaciones matemáticas.

TensorFlow contiene todas las operaciones básicas. Puedes comenzar con uno simple. Va a utilizar el método TensorFlow para calcular el cuadrado de un número. Esta operación es sencilla porque solo se requiere un argumento para construir el tensor.

El cuadrado de un número se construye con tf.sqrt (x) con x como un número flotante.

In [33]:
x = tf.constant([2.0], dtype=tf.float32)


In [34]:
tf.sqrt(x)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.4142135], dtype=float32)>

Nota: La salida devolvió un objeto tensor y no el resultado del cuadrado de 2. En el ejemplo, se imprime la definición del tensor y no la evaluación real de la operación. En la siguiente sección, aprenderá cómo funciona TensorFlow para ejecutar las operaciones.

A continuación se presenta una lista de operaciones de uso común. La idea es la misma. Cada operación requiere uno o más argumentos.

- tf.add (a, b)
- tf.substracto (a, b)
- tf.multiplicar (a, b)
- tf.div (a, b)
- tf.pow (a, b)
- tf.exp (a)
- tf.sqrt (a)

In [35]:
# Add
tensor_a = tf.constant([[1,2]], dtype=tf.int32)
tensor_b = tf.constant([[4,3]], dtype=tf.int32)

tensor_add = tf.add(tensor_a,tensor_b)


In [36]:
tensor_add

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 5]])>

Explicación de código

Cree dos tensores:

un tensor con 1 y 2
un tensor con 3 y 4
Suma ambos tensores.

Aviso: que ambos tensores deben tener la misma forma. Puede ejecutar una multiplicación sobre los dos tensores.

In [37]:
# Multiply
tensor_mul = tf.multiply(tensor_a,tensor_b)
tensor_mul

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 6]])>

In [48]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [47]:
# Crear dos tensores nuevos de dimensión 5x5 y obtener la suma en un nuevo tensor, y la multiplicación en un nuevo tensor
np.random.randint(10,size=(5,5))

array([[5, 5, 8, 8, 7],
       [1, 3, 4, 4, 7],
       [6, 3, 4, 4, 9],
       [2, 5, 3, 4, 5],
       [2, 4, 9, 1, 2]])

### Constantes

#### Definir una constante

In [50]:
# Definir una constante en TensorFlow 2.0
tensor_20=tf.constant([[2,3],[3,6]])
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 6]])>

In [51]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [56]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()

array([[2, 3],
       [3, 6]])

In [57]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
a = np.array([[2,3],[5,8]])
a

array([[2, 3],
       [5, 8]])

In [58]:
tensor3=tf.constant(a)

In [59]:
tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 8]])>

### Variables

#### Definir una variable

In [60]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [61]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [63]:
tf2_variable[0,2].numpy()

3.0

In [64]:
tf2_variable[0,2].assign(100)


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Constantes vs Variables

En TensorFlow, las diferencias entre constantes y variables son que cuando se declara una constante, su valor no se puede cambiar en el futuro (también se inicialización debe ser un valor, no una operación).

Sin embargo, cuando declara una Variable, puede cambiar su valor en el futuro con el método tf.assign()

### Operaciones con tensores

In [66]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

#### Sumar un escalar a un tensor

In [67]:
tensor +2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

#### Multiplicar un escalar por un tensor

In [68]:
tensor*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [69]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [70]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [71]:
np.dot(tensor,tensor_20) 

array([[ 8, 15],
       [18, 33]])

### Strings en TensorFlow 2.0

In [73]:
tf_string = tf.constant('Tensorflow')

In [74]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

#### Operaciones simples con strings

In [76]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [77]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119])>

#### Almacenar arrays de strings

In [79]:
tf_str_array=tf.constant(["hola","como","estás"])

In [80]:
# Iterar sobre un array de strings en TF
for string in tf_str_array:
    print(string)

tf.Tensor(b'hola', shape=(), dtype=string)
tf.Tensor(b'como', shape=(), dtype=string)
tf.Tensor(b'est\xc3\xa1s', shape=(), dtype=string)
